GET  https://mesto.nomoreparties.co/v1/cohort-60/users
content-type: application/json
Authorization: aa8e790a-3250-4e42-83f6-285a574f94a9

############

PATCH  http://127.0.0.1:3000/users/me
content-type: application/json

{
  "name": "user3",
  "about": "userenok1"
}


############

GET  http://127.0.0.1:3000/users
content-type: application/json


############
GET  https://mesto.nomoreparties.co/v1/cohort-60/cards
content-type: application/json

############




##################
GET  http://127.0.0.1:3000/users/64631e8d3f834371da10dcb5

content-type: application/json

##################


POST  http://127.0.0.1:3000/users
content-type: application/json

{ "name": "user1",
  "about": "userenok1",
  "avatar": "https://mobimg.b-cdn.net/v3/fetch/e6/e6631960d3d446633839c78db26f82ce.jpeg"
}

############


GET  http://127.0.0.1:3000/cards
content-type: application/json


############


POST  http://127.0.0.1:3000/cards
content-type: application/json

{ "name": "mesto2",
  "link": "https://mobimg.b-cdn.net/v3/fetch/e6/e6631960d3d446633839c78db26f82ce.jpeg"
}

#########

POST  http://127.0.0.1:3000/cards
content-type: application/json

{ "name": "mesto2",
  "link": "https://mobimg.b-cdn.net/v3/fetch/e6/e6631960d3d446633839c78db26f82ce.jpeg"
}

#############

DELETE  http://127.0.0.1:3000/cards/646339f8387b39dde82bec02
content-type: application/json

#############

PATCH  http://127.0.0.1:3000/users/me/avatar
content-type: application/json

{

  "avatar": "https://mobimg.b-cdn.net446633839c78db26f82ce.jpeg"
}
